### ISSUE TITLE
Update data broker list with new oag.ca.gov registered data brokers

### ISSUE THREAD

**Issue by coreystone** [your-digital-rights/data-brokers#2]
The California Office of the Attorney General's [data broker registry](https://www.oag.ca.gov/data-brokers) is continually updated with new submissions. Since May 2021 (I believe the last time there was an update to this project's broker list), over 160 entries have been added. There are also over 100 pending submissions for 2023 alone which might expand the list soon. 

I suggest adding these new brokers for a more current list if time permits. Are there any guidelines for vetting these brokers to add to the final list? In the .csv, some have notes describing how they respond to or accept requests.

By the way, hats off for the awesome work you guys do.

**Comment by yoavaviram** [comment]
We do this on a regular basis
