### ISSUE TITLE
Rows misaligned in CSV export

### ISSUE THREAD

**Issue by tagawa** [your-digital-rights/data-brokers#3]
**Steps to reproduce:**
1. Go to https://databrokerswatch.org
2. Click "Download the list" and save the CSV file locally.
3. Open the CSV file in LibreOffice, Excel, etc.

**What should happen:**
The data for any particular data broker should be on a single line.

**What actually happens:**
The domain field for each data broker is incorrect – it's vertically offset by 1-3 rows throughout the file. See example screenshots below.

<img width="791" alt="Screenshot 2024-01-16 at 12 12 00" src="https://github.com/your-digital-rights/data-brokers/assets/94173/9b881c8d-af1b-42a1-9b38-40e2f532652e">

<img width="791" alt="Screenshot 2024-01-16 at 12 11 24" src="https://github.com/your-digital-rights/data-brokers/assets/94173/897f72ca-9b3d-40cf-bce0-51962dd748c2">

**Comment by yoavaviram** [comment]
Thanks @tagawa for reporting. Fixed.
